name: Test Nestor - Test CI
on: [pull_request]
jobs:
  Tests: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Node installation
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Dependencies installation
        run: yarn
      - name: Test check
        run: yarn test
